"""create table clients and reservations

Revision ID: 1ea4c155788e
Revises: bbcf6f79e57c
Create Date: 2024-09-05 00:59:04.891585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea4c155788e'
down_revision: Union[str, None] = 'bbcf6f79e57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
