"""create table clients and reservations

Revision ID: 227f8a8440bb
Revises: 
Create Date: 2024-09-07 00:08:54.709062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227f8a8440bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_Clients_full_name'), 'Clients', ['full_name'], unique=False)
    op.create_index(op.f('ix_Clients_id'), 'Clients', ['id'], unique=False)
    op.create_table('Reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_code', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_code')
    )
    op.create_index(op.f('ix_Reservations_id'), 'Reservations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Reservations_id'), table_name='Reservations')
    op.drop_table('Reservations')
    op.drop_index(op.f('ix_Clients_id'), table_name='Clients')
    op.drop_index(op.f('ix_Clients_full_name'), table_name='Clients')
    op.drop_table('Clients')
    # ### end Alembic commands ###
