"""create table clients and reservations

Revision ID: 4613443f6f40
Revises: 6ffc5f0588a4
Create Date: 2024-09-05 01:12:25.381273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4613443f6f40'
down_revision: Union[str, None] = '6ffc5f0588a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
