"""create table clients and reservations

Revision ID: 6ffc5f0588a4
Revises: bc0979c3fa0b
Create Date: 2024-09-05 01:08:28.823345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffc5f0588a4'
down_revision: Union[str, None] = 'bc0979c3fa0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
