"""create hashed_password column

Revision ID: 7e0bf934e0c9
Revises: 3821d729d7e3
Create Date: 2024-09-18 12:48:16.372654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0bf934e0c9'
down_revision: Union[str, None] = '3821d729d7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clients', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clients', 'hashed_password')
    # ### end Alembic commands ###
