"""create table clients and reservations

Revision ID: 83b2e1b5ed9a
Revises: 4613443f6f40
Create Date: 2024-09-05 01:14:23.753134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b2e1b5ed9a'
down_revision: Union[str, None] = '4613443f6f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
